#!/usr/bin/env ruby
require 'sinatra'
require 'sinatra-websocket'

set :server, 'thin'
set :sockets, []

# Alias '/' to '/index.html'
get '/' do
  send_file File.join(settings.public_folder, 'index.html')
end

# Simple echo websocket server
#
# 한 소켓으로부터 데이터가 들어올 경우, 나머지 소켓들에게 그 데이터를 전달한다.
get '/api' do
  request.websocket do |ws|
    ws.onopen { settings.sockets << ws }
    ws.onclose { settings.sockets.delete(ws) }
    ws.onmessage do |msg|
      EM.next_tick { settings.sockets.each { |s| s.send(msg) unless ws == s } }
    end
  end
end
