on: [push, pull_request]

defaults:
  run:
    working-directory: client

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install.cwd: client
          package_json_file: 'client/package.json'
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: client/pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
